Repository RMamonts/nfs-mamont, pull requests merged in 2025-08, with the labels that each got.

#1 Setup: add CI config
  .github/workflows/rust.yml
  rust-toolchain.toml
Labels: enhancement

#24 Add LOCALIO auxiliary RPC protocol branch in RPC handle
  src/protocol/rpc/wire.rs
Labels: bug

#41 fix: remove unused deps in Cargo.toml
  Cargo.lock
  Cargo.toml
Labels: invalid

#39 demofs: refactor: use tokio RwLock and HashMap
  examples/demo_fs/fs.rs
  examples/demo_fs/fs_contents.rs
  examples/demo_fs/fs_entry.rs
Labels: enhancement, refactor

#18 Fix rmdir in DemoFS
  examples/demo_fs/fs.rs
  examples/demo_fs/fs_entry.rs
Labels: bug

#94 NVSv4 server state
  src/protocol/nfs/v4/mod.rs
  src/protocol/xdr/nfs4/mod.rs
  src/vfs.rs
Labels: help wanted
